<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerX29Eex3\srcApp_KernelTestDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerX29Eex3/srcApp_KernelTestDebugContainer.php') {
    touch(__DIR__.'/ContainerX29Eex3.legacy');

    return;
}

if (!\class_exists(srcApp_KernelTestDebugContainer::class, false)) {
    \class_alias(\ContainerX29Eex3\srcApp_KernelTestDebugContainer::class, srcApp_KernelTestDebugContainer::class, false);
}

return new \ContainerX29Eex3\srcApp_KernelTestDebugContainer([
    'container.build_hash' => 'X29Eex3',
    'container.build_id' => 'de82dbac',
    'container.build_time' => 1564505342,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerX29Eex3');
