<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container4xnODI8\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container4xnODI8/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container4xnODI8.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container4xnODI8\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \Container4xnODI8\srcApp_KernelDevDebugContainer([
    'container.build_hash' => '4xnODI8',
    'container.build_id' => '285bdc03',
    'container.build_time' => 1564134854,
], __DIR__.\DIRECTORY_SEPARATOR.'Container4xnODI8');
