<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container3cxbftJ\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container3cxbftJ/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container3cxbftJ.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container3cxbftJ\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \Container3cxbftJ\srcApp_KernelDevDebugContainer([
    'container.build_hash' => '3cxbftJ',
    'container.build_id' => 'dc902cf0',
    'container.build_time' => 1564400809,
], __DIR__.\DIRECTORY_SEPARATOR.'Container3cxbftJ');
